name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        use: true
    - name: Build
      run: |
        docker build . -f Dockerfile -t docker.io/${{ secrets.DOCKER_USERNAME }}/agedraw
